<?php
# Check for newer version
if(Library_Data_Version::check())
{ ?>
            <div class="header corner full-size padding" style="float:left; text-align:center; margin-top:10px;">
            A newer version of phpMemcachedAdmin may be available , visit the <a href="https://github.com/wp-cloud/phpmemcacheadmin" target="_blank">GitHub repo</a> to know more.
<?php
} else { ?>
			<div class="sub-header corner full-size padding" style="float:left; text-align:center; margin-top:10px;">
                <a href="https://github.com/wp-cloud/phpmemcacheadmin" target="_blank">phpMemcachedAdmin on GitHub</a> -
                <a href="http://memcached.org/" target="_blank">Memcached.org</a>
<?php
} ?>
            </div>
        </div>
    </body>
</html>